//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sponge.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   https://get.adobe.com/reader/?region=US과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AdobeReaderUrl {
            get {
                return ResourceManager.GetString("AdobeReaderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TableCloth - Keep Your Computer Sound &amp; Safe!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppCommentText {
            get {
                return ResourceManager.GetString("AppCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (c) 2021 Jung Hyun, Nam과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://yourtablecloth.app과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppInfoUrl {
            get {
                return ResourceManager.GetString("AppInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TableCloth과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TableCloth Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppPublisher {
            get {
                return ResourceManager.GetString("AppPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/yourtablecloth/TableCloth/releases과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppUpdateInfoUrl {
            get {
                return ResourceManager.GetString("AppUpdateInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Banking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_Banking {
            get {
                return ResourceManager.GetString("DisplayName_Banking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credit Card과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_CreditCard {
            get {
                return ResourceManager.GetString("DisplayName_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Education과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_Education {
            get {
                return ResourceManager.GetString("DisplayName_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_Favorite {
            get {
                return ResourceManager.GetString("DisplayName_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loans/Finance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_Financing {
            get {
                return ResourceManager.GetString("DisplayName_Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Government과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_Government {
            get {
                return ResourceManager.GetString("DisplayName_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insurance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_Insurance {
            get {
                return ResourceManager.GetString("DisplayName_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_Other {
            get {
                return ResourceManager.GetString("DisplayName_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Securities/Investments과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisplayName_Security {
            get {
                return ResourceManager.GetString("DisplayName_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://modu-print.com/과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EveryonesPrinterUrl {
            get {
                return ResourceManager.GetString("EveryonesPrinterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.hancom.com/cs_center/csDownload.do과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HancomOfficeViewerUrl {
            get {
                return ResourceManager.GetString("HancomOfficeViewerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://yourtablecloth.app/privacy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.raidrive.com/download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RaiDriveUrl {
            get {
                return ResourceManager.GetString("RaiDriveUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.google.com/과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnboundHomeUrl {
            get {
                return ResourceManager.GetString("UnboundHomeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
    }
}
