//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://get.adobe.com/kr/reader/.
        /// </summary>
        internal static string AdobeReaderUrl {
            get {
                return ResourceManager.GetString("AdobeReaderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 - 컴퓨터를 깨끗하게 사용하세요!.
        /// </summary>
        internal static string AppCommentText {
            get {
                return ResourceManager.GetString("AppCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth - Keep your computer clean!.
        /// </summary>
        internal static string AppCommentTextForWixAndStore {
            get {
                return ResourceManager.GetString("AppCommentTextForWixAndStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app.
        /// </summary>
        internal static string AppContactForWixAndStore {
            get {
                return ResourceManager.GetString("AppContactForWixAndStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) 2021 남정현.
        /// </summary>
        internal static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app.
        /// </summary>
        internal static string AppInfoUrl {
            get {
                return ResourceManager.GetString("AppInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth.
        /// </summary>
        internal static string AppNameForWixAndStore {
            get {
                return ResourceManager.GetString("AppNameForWixAndStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 프로젝트.
        /// </summary>
        internal static string AppPublisher {
            get {
                return ResourceManager.GetString("AppPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth Project.
        /// </summary>
        internal static string AppPublisherForWixAndStore {
            get {
                return ResourceManager.GetString("AppPublisherForWixAndStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/yourtablecloth/TableCloth/releases.
        /// </summary>
        internal static string AppUpdateInfoUrl {
            get {
                return ResourceManager.GetString("AppUpdateInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app/TableClothCatalog/Catalog.xml.
        /// </summary>
        internal static string CatalogUrl {
            get {
                return ResourceManager.GetString("CatalogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://modu-print.com/.
        /// </summary>
        internal static string EveryonesPrinterUrl {
            get {
                return ResourceManager.GetString("EveryonesPrinterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hancom.com/cs_center/csDownload.do.
        /// </summary>
        internal static string HancomOfficeViewerUrl {
            get {
                return ResourceManager.GetString("HancomOfficeViewerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app/TableClothCatalog/sites.xml.
        /// </summary>
        internal static string IEModePolicyXmlUrl {
            get {
                return ResourceManager.GetString("IEModePolicyXmlUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app/TableClothCatalog/images.
        /// </summary>
        internal static string ImageUrlPrefix {
            get {
                return ResourceManager.GetString("ImageUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app/privacy.
        /// </summary>
        internal static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.raidrive.com/download.
        /// </summary>
        internal static string RaiDriveUrl {
            get {
                return ResourceManager.GetString("RaiDriveUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://785e3f46849c403bb6c323d7a9eaad91@o77541.ingest.sentry.io/5915832.
        /// </summary>
        internal static string SentryDsn {
            get {
                return ResourceManager.GetString("SentryDsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36.
        /// </summary>
        internal static string UserAgentText {
            get {
                return ResourceManager.GetString("UserAgentText", resourceCulture);
            }
        }
    }
}
