//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://get.adobe.com/kr/reader/.
        /// </summary>
        public static string AdobeReaderUrl {
            get {
                return ResourceManager.GetString("AdobeReaderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 - 컴퓨터를 깨끗하게 사용하세요!.
        /// </summary>
        public static string AppCommentText {
            get {
                return ResourceManager.GetString("AppCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) 2021 남정현.
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app.
        /// </summary>
        public static string AppInfoUrl {
            get {
                return ResourceManager.GetString("AppInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 프로젝트.
        /// </summary>
        public static string AppPublisher {
            get {
                return ResourceManager.GetString("AppPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/yourtablecloth/TableCloth/releases.
        /// </summary>
        public static string AppUpdateInfoUrl {
            get {
                return ResourceManager.GetString("AppUpdateInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 뱅킹.
        /// </summary>
        public static string DisplayName_Banking {
            get {
                return ResourceManager.GetString("DisplayName_Banking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 신용 카드.
        /// </summary>
        public static string DisplayName_CreditCard {
            get {
                return ResourceManager.GetString("DisplayName_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교육.
        /// </summary>
        public static string DisplayName_Education {
            get {
                return ResourceManager.GetString("DisplayName_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 대출/금융.
        /// </summary>
        public static string DisplayName_Financing {
            get {
                return ResourceManager.GetString("DisplayName_Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공공.
        /// </summary>
        public static string DisplayName_Government {
            get {
                return ResourceManager.GetString("DisplayName_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보험.
        /// </summary>
        public static string DisplayName_Insurance {
            get {
                return ResourceManager.GetString("DisplayName_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기타.
        /// </summary>
        public static string DisplayName_Other {
            get {
                return ResourceManager.GetString("DisplayName_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 증권/투자.
        /// </summary>
        public static string DisplayName_Security {
            get {
                return ResourceManager.GetString("DisplayName_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://modu-print.com/.
        /// </summary>
        public static string EveryonesPrinterUrl {
            get {
                return ResourceManager.GetString("EveryonesPrinterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hancom.com/cs_center/csDownload.do.
        /// </summary>
        public static string HancomOfficeViewerUrl {
            get {
                return ResourceManager.GetString("HancomOfficeViewerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app/privacy.
        /// </summary>
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.raidrive.com/download.
        /// </summary>
        public static string RaiDriveUrl {
            get {
                return ResourceManager.GetString("RaiDriveUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.naver.com/.
        /// </summary>
        public static string UnboundHomeUrl {
            get {
                return ResourceManager.GetString("UnboundHomeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알 수 없음.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
    }
}
