//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstantStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.ConstantStrings", typeof(ConstantStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth - Keep your computer clean!.
        /// </summary>
        public static string AppCommentTextForWixAndStore {
            get {
                return ResourceManager.GetString("AppCommentTextForWixAndStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app.
        /// </summary>
        public static string AppContactForWixAndStore {
            get {
                return ResourceManager.GetString("AppContactForWixAndStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth.
        /// </summary>
        public static string AppNameForWixAndStore {
            get {
                return ResourceManager.GetString("AppNameForWixAndStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth Project.
        /// </summary>
        public static string AppPublisherForWixAndStore {
            get {
                return ResourceManager.GetString("AppPublisherForWixAndStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app/TableClothCatalog/Catalog.xml.
        /// </summary>
        public static string CatalogUrl {
            get {
                return ResourceManager.GetString("CatalogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github.com.
        /// </summary>
        public static string GitHub_Domain {
            get {
                return ResourceManager.GetString("GitHub_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app/TableClothCatalog/sites.xml.
        /// </summary>
        public static string IEModePolicyXmlUrl {
            get {
                return ResourceManager.GetString("IEModePolicyXmlUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app/TableClothCatalog/images.
        /// </summary>
        public static string ImageUrlPrefix {
            get {
                return ResourceManager.GetString("ImageUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9N46Z3N6T2VR.
        /// </summary>
        public static string MicrosoftStore_ProductId {
            get {
                return ResourceManager.GetString("MicrosoftStore_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko.
        /// </summary>
        public static string OldUserAgentText {
            get {
                return ResourceManager.GetString("OldUserAgentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ts.
        /// </summary>
        public static string QueryString_Timestamp_Key {
            get {
                return ResourceManager.GetString("QueryString_Timestamp_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://785e3f46849c403bb6c323d7a9eaad91@o77541.ingest.sentry.io/5915832.
        /// </summary>
        public static string SentryDsn {
            get {
                return ResourceManager.GetString("SentryDsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --cert-private-key.
        /// </summary>
        public static string TableCloth_Switch_CertPrivateKey {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --cert-public-key.
        /// </summary>
        public static string TableCloth_Switch_CertPublicKey {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --dry-run.
        /// </summary>
        public static string TableCloth_Switch_DryRun {
            get {
                return ResourceManager.GetString("TableCloth_Switch_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --enable-camera.
        /// </summary>
        public static string TableCloth_Switch_EnableCamera {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --enable-cert.
        /// </summary>
        public static string TableCloth_Switch_EnableCert {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --enable-ie-mode.
        /// </summary>
        public static string TableCloth_Switch_EnableIEMode {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableIEMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --enable-microphone.
        /// </summary>
        public static string TableCloth_Switch_EnableMicrophone {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --enable-printer.
        /// </summary>
        public static string TableCloth_Switch_EnablePrinter {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnablePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --help.
        /// </summary>
        public static string TableCloth_Switch_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --ignore--.
        /// </summary>
        public static string TableCloth_Switch_IgnoreSwitch {
            get {
                return ResourceManager.GetString("TableCloth_Switch_IgnoreSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --install-adobe-reader.
        /// </summary>
        public static string TableCloth_Switch_InstallAdobeReader {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallAdobeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --install-everyones-printer.
        /// </summary>
        public static string TableCloth_Switch_InstallEveryonesPrinter {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallEveryonesPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --install-hancom-office-viewer.
        /// </summary>
        public static string TableCloth_Switch_InstallHancomOfficeViewer {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallHancomOfficeViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --install-rai-drive.
        /// </summary>
        public static string TableCloth_Switch_InstallRaiDrive {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallRaiDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        public static string TableCloth_Switch_Prefix {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --simulate-failure.
        /// </summary>
        public static string TableCloth_Switch_SimulateFailure {
            get {
                return ResourceManager.GetString("TableCloth_Switch_SimulateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36.
        /// </summary>
        public static string UserAgentText {
            get {
                return ResourceManager.GetString("UserAgentText", resourceCulture);
            }
        }
    }
}
