//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.DialogStrings", typeof(DialogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용 가능.
        /// </summary>
        public static string Cert_Availability_Available {
            get {
                return ResourceManager.GetString("Cert_Availability_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 만료됨.
        /// </summary>
        public static string Cert_Availability_Expired {
            get {
                return ResourceManager.GetString("Cert_Availability_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}일 후 만료.
        /// </summary>
        public static string Cert_Availability_ExpireSoon {
            get {
                return ResourceManager.GetString("Cert_Availability_ExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}일 후 사용 가능.
        /// </summary>
        public static string Cert_Availability_MayTooEarly {
            get {
                return ResourceManager.GetString("Cert_Availability_MayTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지금부터 {0}개 프로그램의 설치 과정이 시작됩니다. 모든 프로그램의 설치가 끝나면 자동으로 {1} 홈페이지가 열립니다..
        /// </summary>
        public static string Script_InstructionMessage {
            get {
                return ResourceManager.GetString("Script_InstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 안내.
        /// </summary>
        public static string Script_InstructionTitleText {
            get {
                return ResourceManager.GetString("Script_InstructionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인터넷 연결 상태 확인 중....
        /// </summary>
        public static string Status_CheckInternetConnection {
            get {
                return ResourceManager.GetString("Status_CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 실행 준비가 완료되었습니다..
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 환경 확인 중....
        /// </summary>
        public static string Status_EvaluatingRequirementsMet {
            get {
                return ResourceManager.GetString("Status_EvaluatingRequirementsMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 애플리케이션 초기화 중....
        /// </summary>
        public static string Status_InitializingApplication {
            get {
                return ResourceManager.GetString("Status_InitializingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오류가 발생했습니다..
        /// </summary>
        public static string Status_InitializingFailed {
            get {
                return ResourceManager.GetString("Status_InitializingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentry SDK 초기화 중....
        /// </summary>
        public static string Status_InitSentrySDK {
            get {
                return ResourceManager.GetString("Status_InitSentrySDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카탈로그 불러오는 중....
        /// </summary>
        public static string Status_LoadingCatalog {
            get {
                return ResourceManager.GetString("Status_LoadingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미지 불러오는 중....
        /// </summary>
        public static string Status_LoadingImages {
            get {
                return ResourceManager.GetString("Status_LoadingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 환경 설정 불러오는 중....
        /// </summary>
        public static string Status_LoadingPreferences {
            get {
                return ResourceManager.GetString("Status_LoadingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령줄 분석 중....
        /// </summary>
        public static string Status_ParsingCommandLine {
            get {
                return ResourceManager.GetString("Status_ParsingCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 오류.
        /// </summary>
        public static string TitleText_Error {
            get {
                return ResourceManager.GetString("TitleText_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 정보.
        /// </summary>
        public static string TitleText_Info {
            get {
                return ResourceManager.GetString("TitleText_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 확인.
        /// </summary>
        public static string TitleText_Question {
            get {
                return ResourceManager.GetString("TitleText_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 경고.
        /// </summary>
        public static string TitleText_Warning {
            get {
                return ResourceManager.GetString("TitleText_Warning", resourceCulture);
            }
        }
    }
}
