//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The TableCloth program is already running.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Already_TableCloth_Running {
            get {
                return ResourceManager.GetString("Error_Already_TableCloth_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data could not be copied because the clipboard was not ready.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_CopyToClipboard {
            get {
                return ResourceManager.GetString("Error_Cannot_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create a directory for storing application data.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Create_AppDataDirectory {
            get {
                return ResourceManager.GetString("Error_Cannot_Create_AppDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The catalog file was not downloaded.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Download_Catalog {
            get {
                return ResourceManager.GetString("Error_Cannot_Download_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The certificate information file (.der) file was not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Find_CertFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_CertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The certificate private key file (.key) file was not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Find_KeyFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_KeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The certificate file (.pfx or .p12) file was not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Find_PfxFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_PfxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application called the Windows OS product information lookup API, but was unable to get the information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Invoke_GetProductInfo {
            get {
                return ResourceManager.GetString("Error_Cannot_Invoke_GetProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The call to the Get Windows OS version information API failed with the following error code - {0:X8}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Invoke_GetVersionEx {
            get {
                return ResourceManager.GetString("Error_Cannot_Invoke_GetVersionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get assembly information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Obtain_Assembly {
            get {
                return ResourceManager.GetString("Error_Cannot_Obtain_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application content creation task failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Prepare_AppContents {
            get {
                return ResourceManager.GetString("Error_Cannot_Prepare_AppContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application can&apos;t run the System Information utility.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Run_SysInfo {
            get {
                return ResourceManager.GetString("Error_Cannot_Run_SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of the Catalog.xml file seems to be different from what the program expects.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_CatalogDeserilizationFailure {
            get {
                return ResourceManager.GetString("Error_CatalogDeserilizationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The program can&apos;t proceed with the installation because the Catalog.xml file can&apos;t be loaded from a remote website.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_CatalogLoadFailure {
            get {
                return ResourceManager.GetString("Error_CatalogLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The certificate you selected has expired. You&apos;ll need to select a different public certificate, or replace it with a new public certificate.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cert_Expired {
            get {
                return ResourceManager.GetString("Error_Cert_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expires in {0} days. It needs to be replaced with a new certificate.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cert_ExpireSoon {
            get {
                return ResourceManager.GetString("Error_Cert_ExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The certificate you selected will be available in {0} days.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cert_MayTooEarly {
            get {
                return ResourceManager.GetString("Error_Cert_MayTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows Command Line Interpreter (cmd.exe) could not be found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_CommandLineInterpreter_Missing {
            get {
                return ResourceManager.GetString("Error_CommandLineInterpreter_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to prepare a directory to store data files for use inside the sandbox.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Fail_PrepareAssetDirectory {
            get {
                return ResourceManager.GetString("Error_Fail_PrepareAssetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (File: {0} (Row: {1}), Member: {2})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_FileLineNo {
            get {
                return ResourceManager.GetString("Error_FileLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For reference, here&apos;s the error occurred - {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_ForYourReference {
            get {
                return ResourceManager.GetString("Error_ForYourReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected Error: Cannot find help switch from command line parser configuration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_HelpSwitch_NotFound {
            get {
                return ResourceManager.GetString("Error_HelpSwitch_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following directories are not found on this computer and will not be mounted when connecting from the sandbox.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_HostFolder_Unavailable {
            get {
                return ResourceManager.GetString("Error_HostFolder_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_HostFolder_Unavailable_Item {
            get {
                return ResourceManager.GetString("Error_HostFolder_Unavailable_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to confirm support for system virtualization features, Windows Sandbox may not run properly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_HyperVisor_Missing {
            get {
                return ResourceManager.GetString("Error_HyperVisor_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internet Explorer mode must be enabled within the Microsoft Edge browser to avoid compatibility issues. Please enable Internet Explorer via Add/Remove System Components.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_IEMode_NotAvailable {
            get {
                return ResourceManager.GetString("Error_IEMode_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The default image and icon resource files were not found, please reinstall the program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Images_Missing {
            get {
                return ResourceManager.GetString("Error_Images_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The installation script could not be run because the Windows PowerShell executable file was not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_No_WindowsPowerShell {
            get {
                return ResourceManager.GetString("Error_No_WindowsPowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It looks like your system is not connected to the internet, please connect to the internet and run the TableCloth program again for full functionality.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Offline {
            get {
                return ResourceManager.GetString("Error_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select one certificate information file (DER) and one certificate private key file (KEY).
        ///
        ///You can select multiple files by holding down the Ctrl or Shift key, or by dragging an empty space in the file selection window.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_OpenDerAndKey_Simultaneously {
            get {
                return ResourceManager.GetString("Error_OpenDerAndKey_Simultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The package installer failed to start.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Package_CanNotStart {
            get {
                return ResourceManager.GetString("Error_Package_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After installing Windows Sandbox, you may need to restart your system. If necessary, restart your system and run TableCloth again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Restart_And_RunAgain {
            get {
                return ResourceManager.GetString("Error_Restart_And_RunAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Based on the product information retrieved, it appears that you are using a version of the operating system that does not support the Windows Sandbox feature.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_SandboxMightNotAvailable {
            get {
                return ResourceManager.GetString("Error_SandboxMightNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut creation failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_ShortcutFailed {
            get {
                return ResourceManager.GetString("Error_ShortcutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t create a shortcut because there is no website selected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_ShortcutNoSiteSelected {
            get {
                return ResourceManager.GetString("Error_ShortcutNoSiteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The spork executable file was not found, please reinstall the program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Spork_Missing {
            get {
                return ResourceManager.GetString("Error_Spork_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application can&apos;t run the AhnLab Safe Transaction configuration utility.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_StSessConfig_CanNotStart {
            get {
                return ResourceManager.GetString("Error_StSessConfig_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred: (File: {0} (Row: {1}), Member: {2})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected Error: Cannot find version switch from command line parser configuration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_VersionSwitch_NotFound {
            get {
                return ResourceManager.GetString("Error_VersionSwitch_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TableCloth can&apos;t proceed with the Windows Sandbox installation surrogate because the DISM.exe utility was not found. You can try enabling Windows Sandbox in Turn Windows Features On/Off.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Windows_Dism_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Dism_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application can&apos;t start the Windows Explorer program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Windows_Explorer_CanNotStart {
            get {
                return ResourceManager.GetString("Error_Windows_Explorer_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Windows Explorer program was not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Windows_Explorer_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Explorer_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operating system you are running appears to be an older version of an operating system that does not support the Windows Sandbox feature. Please upgrade to Windows 10 or later.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Windows_OS_Too_Old {
            get {
                return ResourceManager.GetString("Error_Windows_OS_Too_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It looks like you&apos;re running Windows Sandbox through the TableCloth, please exit Windows Sandbox first when you&apos;re done using it.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Windows_Sandbox_Already_Running {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_Already_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to run the sandbox program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Windows_Sandbox_CanNotStart {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It looks like you don&apos;t have Windows Sandbox installed! Please enable Windows Sandbox in Turn Windows Features On/Off.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Windows_Sandbox_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An X509 certificate error occurred during communication with a remote website. The certificate subject is {0}, and the error code encountered is {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_X509CertError {
            get {
                return ResourceManager.GetString("Error_X509CertError", resourceCulture);
            }
        }
    }
}
