//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 식탁보 프로그램이 실행되고 있어요..
        /// </summary>
        public static string Error_Already_TableCloth_Running {
            get {
                return ResourceManager.GetString("Error_Already_TableCloth_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 애플리케이션 데이터 저장을 위한 디렉터리를 만들지 못했습니다..
        /// </summary>
        public static string Error_Cannot_Create_AppDataDirectory_Message_1 {
            get {
                return ResourceManager.GetString("Error_Cannot_Create_AppDataDirectory_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 참고로, 발생했던 오류는 다음과 같습니다 - {0}.
        /// </summary>
        public static string Error_Cannot_Create_AppDataDirectory_Message_2 {
            get {
                return ResourceManager.GetString("Error_Cannot_Create_AppDataDirectory_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카탈로그 파일을 내려받지 못했습니다..
        /// </summary>
        public static string Error_Cannot_Download_Catalog_Message_1 {
            get {
                return ResourceManager.GetString("Error_Cannot_Download_Catalog_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 참고로, 발생했던 오류는 다음과 같습니다 - {0}.
        /// </summary>
        public static string Error_Cannot_Download_Catalog_Message_2 {
            get {
                return ResourceManager.GetString("Error_Cannot_Download_Catalog_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공동 인증서 정보 파일 (.der) 파일을 찾을 수 없습니다..
        /// </summary>
        public static string Error_Cannot_Find_CertFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_CertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공동 인증서 개인 키 파일 (.key) 파일을 찾을 수 없습니다..
        /// </summary>
        public static string Error_Cannot_Find_KeyFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_KeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공동 인증서 파일 (.pfx 또는 .p12) 파일을 찾을 수 없습니다..
        /// </summary>
        public static string Error_Cannot_Find_PfxFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_PfxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윈도우 OS 제품 정보 조회 API를 호출했지만, 정보를 가져올 수 없습니다..
        /// </summary>
        public static string Error_Cannot_Invoke_GetProductInfo {
            get {
                return ResourceManager.GetString("Error_Cannot_Invoke_GetProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윈도우 OS 버전 정보 조회 API를 호출했지만, 다음의 오류 코드와 함께 실패했습니다 - {0:X8}.
        /// </summary>
        public static string Error_Cannot_Invoke_GetVersionEx {
            get {
                return ResourceManager.GetString("Error_Cannot_Invoke_GetVersionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 어셈블리 정보를 가져올 수 없습니다..
        /// </summary>
        public static string Error_Cannot_Obtain_Assembly {
            get {
                return ResourceManager.GetString("Error_Cannot_Obtain_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 애플리케이션 콘텐츠 생성 작업을 진행하지 못했습니다..
        /// </summary>
        public static string Error_Cannot_Prepare_AppContents_Message_1 {
            get {
                return ResourceManager.GetString("Error_Cannot_Prepare_AppContents_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 참고로, 발생했던 오류는 다음과 같습니다 - {0}.
        /// </summary>
        public static string Error_Cannot_Prepare_AppContents_Message_2 {
            get {
                return ResourceManager.GetString("Error_Cannot_Prepare_AppContents_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 정보 유틸리티를 실행할 수 없습니다..
        /// </summary>
        public static string Error_Cannot_Run_SysInfo {
            get {
                return ResourceManager.GetString("Error_Cannot_Run_SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택하신 공동 인증서는 만료되었습니다. 다른 공동 인증서를 선택하거나, 새로운 공동 인증서로 교체 발급해야 합니다..
        /// </summary>
        public static string Error_Cert_Expired {
            get {
                return ResourceManager.GetString("Error_Cert_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}일 후에 만료됩니다. 새로운 공동 인증서로 교체가 필요합니다..
        /// </summary>
        public static string Error_Cert_ExpireSoon {
            get {
                return ResourceManager.GetString("Error_Cert_ExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택하신 공동 인증서는 {0}일 후부터 사용 가능합니다..
        /// </summary>
        public static string Error_Cert_MayTooEarly {
            get {
                return ResourceManager.GetString("Error_Cert_MayTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 샌드박스 자동 설치 프로그램 파일을 찾을 수 없습니다. 프로그램을 다시 설치해주세요..
        /// </summary>
        public static string Error_Hostess_Missing {
            get {
                return ResourceManager.GetString("Error_Hostess_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다음의 디렉터리를 이 컴퓨터에서 찾을 수 없어 샌드박스에서 연결할 때 제외합니다..
        /// </summary>
        public static string Error_HostFolder_Unavailable {
            get {
                return ResourceManager.GetString("Error_HostFolder_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}.
        /// </summary>
        public static string Error_HostFolder_Unavailable_Item {
            get {
                return ResourceManager.GetString("Error_HostFolder_Unavailable_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 가상화 기능 지원 여부를 확인할 수 없습니다. 윈도우 샌드박스가 정상적으로 실행되지 않을 가능성이 있습니다..
        /// </summary>
        public static string Error_HyperVisor_Missing {
            get {
                return ResourceManager.GetString("Error_HyperVisor_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Edge 브라우저 안에서 인터넷 익스플로러 모드를 활성화해야 호환성 문제를 피할 수 있습니다. 인터넷 익스플로러를 시스템 구성 요소 추가/제거를 통해 활성화해주세요..
        /// </summary>
        public static string Error_IEMode_NotAvailable {
            get {
                return ResourceManager.GetString("Error_IEMode_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기본 이미지와 아이콘 리소스 파일을 찾을 수 없습니다. 프로그램을 다시 설치해주세요..
        /// </summary>
        public static string Error_Images_Missing {
            get {
                return ResourceManager.GetString("Error_Images_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템이 인터넷과 연결되지 않은 것 같습니다. 모든 기능을 사용하려면 인터넷에 연결한 후 식탁보 프로그램을 다시 실행해 주세요..
        /// </summary>
        public static string Error_Offline {
            get {
                return ResourceManager.GetString("Error_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공동 인증서 정보 파일 (der)과 공동 인증서 개인 키 파일 (key)을 각각 하나씩 선택해주세요.
        ///
        ///Ctrl 키나 Shift 키를 누른 채로 선택하거나, 파일 선택 창에서 빈 공간을 드래그하면 여러 파일을 선택할 수 있어요..
        /// </summary>
        public static string Error_OpenDerAndKey_Simultaneously {
            get {
                return ResourceManager.GetString("Error_OpenDerAndKey_Simultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윈도우 샌드박스를 설치한 후에는 시스템을 다시 시작해야 할 수 있습니다. 필요한 경우 시스템을 다시 시작하고, 식탁보를 다시 실행해주시기 바랍니다..
        /// </summary>
        public static string Error_Restart_And_RunAgain {
            get {
                return ResourceManager.GetString("Error_Restart_And_RunAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색된 제품 정보에 따르면, 윈도우 샌드박스 기능이 지원되지 않는 버전의 운영 체제를 사용 중인 것 같습니다..
        /// </summary>
        public static string Error_SandboxMightNotAvailable {
            get {
                return ResourceManager.GetString("Error_SandboxMightNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바로 가기 생성에 실패했습니다..
        /// </summary>
        public static string Error_ShortcutFailed {
            get {
                return ResourceManager.GetString("Error_ShortcutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택된 웹 사이트가 없어 바로 가기를 생성할 수 없습니다..
        /// </summary>
        public static string Error_ShortcutNoSiteSelected {
            get {
                return ResourceManager.GetString("Error_ShortcutNoSiteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예기치 않은 오류가 발생했습니다. (파일: {0} (행: {1}), 멤버: {2}).
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISM.exe 유틸리티를 찾을 수 없어 식탁보가 Windows 샌드박스 설치 대리 실행을 진행할 수 없습니다. 윈도우 기능 켜기/끄기에서 윈도우 샌드박스를 활성화하는 것을 시도해볼 수 있습니다..
        /// </summary>
        public static string Error_Windows_Dism_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Dism_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윈도우 탐색기 프로그램을 시작할 수 없습니다..
        /// </summary>
        public static string Error_Windows_Explorer_CanNotStart {
            get {
                return ResourceManager.GetString("Error_Windows_Explorer_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윈도우 탐색기 프로그램을 찾을 수 없습니다..
        /// </summary>
        public static string Error_Windows_Explorer_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Explorer_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 실행하고 있는 운영 체제는 윈도우 샌드박스 기능을 지원하지 않는 오래된 버전의 운영 체제 같습니다. 윈도우 10 이상으로 업그레이드 해주세요..
        /// </summary>
        public static string Error_Windows_OS_Too_Old {
            get {
                return ResourceManager.GetString("Error_Windows_OS_Too_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보를 통해서 윈도우 샌드박스를 실행하고 있는 것 같습니다. 사용을 마친 후 윈도우 샌드박스를 먼저 종료해주세요..
        /// </summary>
        public static string Error_Windows_Sandbox_Already_Running {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_Already_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 샌드박스 프로그램을 실행하지 못했습니다..
        /// </summary>
        public static string Error_Windows_Sandbox_CanNotStart {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윈도우 샌드박스가 설치되어있지 않은 것 같습니다! 윈도우 기능 켜기/끄기에서 윈도우 샌드박스를 활성화해주세요..
        /// </summary>
        public static string Error_Windows_Sandbox_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_Missing", resourceCulture);
            }
        }
    }
}
