//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TableCloth program is already running..
        /// </summary>
        public static string Error_Already_TableCloth_Running {
            get {
                return ResourceManager.GetString("Error_Already_TableCloth_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data could not be copied because the clipboard was not ready..
        /// </summary>
        public static string Error_Cannot_CopyToClipboard {
            get {
                return ResourceManager.GetString("Error_Cannot_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a directory for storing application data..
        /// </summary>
        public static string Error_Cannot_Create_AppDataDirectory {
            get {
                return ResourceManager.GetString("Error_Cannot_Create_AppDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The catalog file was not downloaded..
        /// </summary>
        public static string Error_Cannot_Download_Catalog {
            get {
                return ResourceManager.GetString("Error_Cannot_Download_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate information file (.der) file was not found..
        /// </summary>
        public static string Error_Cannot_Find_CertFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_CertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate private key file (.key) file was not found..
        /// </summary>
        public static string Error_Cannot_Find_KeyFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_KeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate file (.pfx or .p12) file was not found..
        /// </summary>
        public static string Error_Cannot_Find_PfxFile {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_PfxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application called the Windows OS product information lookup API, but was unable to get the information..
        /// </summary>
        public static string Error_Cannot_Invoke_GetProductInfo {
            get {
                return ResourceManager.GetString("Error_Cannot_Invoke_GetProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the Get Windows OS version information API failed with the following error code - {0:X8}.
        /// </summary>
        public static string Error_Cannot_Invoke_GetVersionEx {
            get {
                return ResourceManager.GetString("Error_Cannot_Invoke_GetVersionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get assembly information..
        /// </summary>
        public static string Error_Cannot_Obtain_Assembly {
            get {
                return ResourceManager.GetString("Error_Cannot_Obtain_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application content creation task failed..
        /// </summary>
        public static string Error_Cannot_Prepare_AppContents {
            get {
                return ResourceManager.GetString("Error_Cannot_Prepare_AppContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application can&apos;t run the System Information utility..
        /// </summary>
        public static string Error_Cannot_Run_SysInfo {
            get {
                return ResourceManager.GetString("Error_Cannot_Run_SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the Catalog.xml file seems to be different from what the program expects..
        /// </summary>
        public static string Error_CatalogDeserilizationFailure {
            get {
                return ResourceManager.GetString("Error_CatalogDeserilizationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program can&apos;t proceed with the installation because the Catalog.xml file can&apos;t be loaded from a remote website..
        /// </summary>
        public static string Error_CatalogLoadFailure {
            get {
                return ResourceManager.GetString("Error_CatalogLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate you selected has expired. You&apos;ll need to select a different public certificate, or replace it with a new public certificate..
        /// </summary>
        public static string Error_Cert_Expired {
            get {
                return ResourceManager.GetString("Error_Cert_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in {0} days. It needs to be replaced with a new certificate..
        /// </summary>
        public static string Error_Cert_ExpireSoon {
            get {
                return ResourceManager.GetString("Error_Cert_ExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate you selected will be available in {0} days..
        /// </summary>
        public static string Error_Cert_MayTooEarly {
            get {
                return ResourceManager.GetString("Error_Cert_MayTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Command Line Interpreter (cmd.exe) could not be found..
        /// </summary>
        public static string Error_CommandLineInterpreter_Missing {
            get {
                return ResourceManager.GetString("Error_CommandLineInterpreter_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare a directory to store data files for use inside the sandbox..
        /// </summary>
        public static string Error_Fail_PrepareAssetDirectory {
            get {
                return ResourceManager.GetString("Error_Fail_PrepareAssetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (File: {0} (Row: {1}), Member: {2}).
        /// </summary>
        public static string Error_FileLineNo {
            get {
                return ResourceManager.GetString("Error_FileLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For reference, here&apos;s the error occurred - {0}.
        /// </summary>
        public static string Error_ForYourReference {
            get {
                return ResourceManager.GetString("Error_ForYourReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sandbox auto-installer file was not found, please reinstall the program..
        /// </summary>
        public static string Error_Hostess_Missing {
            get {
                return ResourceManager.GetString("Error_Hostess_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following directories are not found on this computer and will not be mounted when connecting from the sandbox..
        /// </summary>
        public static string Error_HostFolder_Unavailable {
            get {
                return ResourceManager.GetString("Error_HostFolder_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}.
        /// </summary>
        public static string Error_HostFolder_Unavailable_Item {
            get {
                return ResourceManager.GetString("Error_HostFolder_Unavailable_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to confirm support for system virtualization features, Windows Sandbox may not run properly..
        /// </summary>
        public static string Error_HyperVisor_Missing {
            get {
                return ResourceManager.GetString("Error_HyperVisor_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer mode must be enabled within the Microsoft Edge browser to avoid compatibility issues. Please enable Internet Explorer via Add/Remove System Components..
        /// </summary>
        public static string Error_IEMode_NotAvailable {
            get {
                return ResourceManager.GetString("Error_IEMode_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default image and icon resource files were not found, please reinstall the program..
        /// </summary>
        public static string Error_Images_Missing {
            get {
                return ResourceManager.GetString("Error_Images_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation script could not be run because the Windows PowerShell executable file was not found..
        /// </summary>
        public static string Error_No_WindowsPowerShell {
            get {
                return ResourceManager.GetString("Error_No_WindowsPowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like your system is not connected to the internet, please connect to the internet and run the TableCloth program again for full functionality..
        /// </summary>
        public static string Error_Offline {
            get {
                return ResourceManager.GetString("Error_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one certificate information file (DER) and one certificate private key file (KEY).
        ///
        ///You can select multiple files by holding down the Ctrl or Shift key, or by dragging an empty space in the file selection window..
        /// </summary>
        public static string Error_OpenDerAndKey_Simultaneously {
            get {
                return ResourceManager.GetString("Error_OpenDerAndKey_Simultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package installer failed to start..
        /// </summary>
        public static string Error_Package_CanNotStart {
            get {
                return ResourceManager.GetString("Error_Package_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After installing Windows Sandbox, you may need to restart your system. If necessary, restart your system and run TableCloth again..
        /// </summary>
        public static string Error_Restart_And_RunAgain {
            get {
                return ResourceManager.GetString("Error_Restart_And_RunAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the product information retrieved, it appears that you are using a version of the operating system that does not support the Windows Sandbox feature..
        /// </summary>
        public static string Error_SandboxMightNotAvailable {
            get {
                return ResourceManager.GetString("Error_SandboxMightNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut creation failed..
        /// </summary>
        public static string Error_ShortcutFailed {
            get {
                return ResourceManager.GetString("Error_ShortcutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t create a shortcut because there is no website selected..
        /// </summary>
        public static string Error_ShortcutNoSiteSelected {
            get {
                return ResourceManager.GetString("Error_ShortcutNoSiteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application can&apos;t run the AhnLab Safe Transaction configuration utility..
        /// </summary>
        public static string Error_StSessConfig_CanNotStart {
            get {
                return ResourceManager.GetString("Error_StSessConfig_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: (File: {0} (Row: {1}), Member: {2}).
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth can&apos;t proceed with the Windows Sandbox installation surrogate because the DISM.exe utility was not found. You can try enabling Windows Sandbox in Turn Windows Features On/Off..
        /// </summary>
        public static string Error_Windows_Dism_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Dism_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application can&apos;t start the Windows Explorer program..
        /// </summary>
        public static string Error_Windows_Explorer_CanNotStart {
            get {
                return ResourceManager.GetString("Error_Windows_Explorer_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows Explorer program was not found..
        /// </summary>
        public static string Error_Windows_Explorer_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Explorer_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operating system you are running appears to be an older version of an operating system that does not support the Windows Sandbox feature. Please upgrade to Windows 10 or later..
        /// </summary>
        public static string Error_Windows_OS_Too_Old {
            get {
                return ResourceManager.GetString("Error_Windows_OS_Too_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you&apos;re running Windows Sandbox through the TableCloth, please exit Windows Sandbox first when you&apos;re done using it..
        /// </summary>
        public static string Error_Windows_Sandbox_Already_Running {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_Already_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run the sandbox program..
        /// </summary>
        public static string Error_Windows_Sandbox_CanNotStart {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you don&apos;t have Windows Sandbox installed! Please enable Windows Sandbox in Turn Windows Features On/Off..
        /// </summary>
        public static string Error_Windows_Sandbox_Missing {
            get {
                return ResourceManager.GetString("Error_Windows_Sandbox_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An X509 certificate error occurred during communication with a remote website. The certificate subject is {0}, and the error code encountered is {1}..
        /// </summary>
        public static string Error_X509CertError {
            get {
                return ResourceManager.GetString("Error_X509CertError", resourceCulture);
            }
        }
    }
}
