//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HostessStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HostessStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.HostessStrings", typeof(HostessStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 별도 설치 스크립트.
        /// </summary>
        public static string Hostess_CustomScript_Title {
            get {
                return ResourceManager.GetString("Hostess_CustomScript_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다운로드 중....
        /// </summary>
        public static string Hostess_Download_InProgress {
            get {
                return ResourceManager.GetString("Hostess_Download_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설치 실패.
        /// </summary>
        public static string Hostess_Install_Failed {
            get {
                return ResourceManager.GetString("Hostess_Install_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설치하는 중....
        /// </summary>
        public static string Hostess_Install_InProgress {
            get {
                return ResourceManager.GetString("Hostess_Install_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설치 완료.
        /// </summary>
        public static string Hostess_Install_Succeed {
            get {
                return ResourceManager.GetString("Hostess_Install_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows PowerShell 실행 파일을 찾을 수 없어 설치 스크립트를 실행할 수 없습니다..
        /// </summary>
        public static string Hostess_No_PowerShell_Error {
            get {
                return ResourceManager.GetString("Hostess_No_PowerShell_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이용하려는 웹 사이트 아이디가 지정되지 않았습니다. 샌드박스는 지금부터 사용하실 수 있어요..
        /// </summary>
        public static string Hostess_No_Targets {
            get {
                return ResourceManager.GetString("Hostess_No_Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사이트 이용 시 주의 사항.
        /// </summary>
        public static string Hostess_Warning_Title {
            get {
                return ResourceManager.GetString("Hostess_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.xml 파일의 형식이 프로그램이 기대하는 형식과 다른 것 같습니다..
        /// </summary>
        public static string HostessError_CatalogDeserilizationFailure {
            get {
                return ResourceManager.GetString("HostessError_CatalogDeserilizationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 원격 웹 사이트로부터 Catalog.xml 파일을 불러올 수 없어 설치를 계속 진행할 수 없습니다..
        /// </summary>
        public static string HostessError_CatalogLoadFailure_Message_1 {
            get {
                return ResourceManager.GetString("HostessError_CatalogLoadFailure_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 참고로, 발생했던 오류는 다음과 같습니다 - {0}.
        /// </summary>
        public static string HostessError_CatalogLoadFailure_Message_2 {
            get {
                return ResourceManager.GetString("HostessError_CatalogLoadFailure_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패키지 설치 프로그램을 시작하지 못했습니다..
        /// </summary>
        public static string HostessError_Package_CanNotStart {
            get {
                return ResourceManager.GetString("HostessError_Package_CanNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패키지를 설치하는 도중 오류가 발생했습니다..
        /// </summary>
        public static string HostessError_PackageInstallFailure_Message_1 {
            get {
                return ResourceManager.GetString("HostessError_PackageInstallFailure_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그러나 원인을 파악하지 못했습니다..
        /// </summary>
        public static string HostessError_PackageInstallFailure_Message_2 {
            get {
                return ResourceManager.GetString("HostessError_PackageInstallFailure_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 원격 웹 사이트와의 통신 도중 X509 인증서 오류가 발생했습니다. 인증서 주체는 {0}이며, 발생한 오류 코드는 {1} 입니다..
        /// </summary>
        public static string HostessError_X509CertError {
            get {
                return ResourceManager.GetString("HostessError_X509CertError", resourceCulture);
            }
        }
    }
}
