//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SwitchStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SwitchStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.SwitchStrings", typeof(SwitchStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the path to the certificate secret key file..
        /// </summary>
        public static string TableCloth_Switch_CertPrivateKey_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPrivateKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to the certificate public key file..
        /// </summary>
        public static string TableCloth_Switch_CertPublicKey_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPublicKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Features for developers) Skip installing application packages, changing system settings, and just watch the program run..
        /// </summary>
        public static string TableCloth_Switch_DryRun_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_DryRun_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on the Use video input feature..
        /// </summary>
        public static string TableCloth_Switch_EnableCamera_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCamera_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on certificates as a feature..
        /// </summary>
        public static string TableCloth_Switch_EnableCert_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCert_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Internet Explorer mode..
        /// </summary>
        public static string TableCloth_Switch_EnableIEMode_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableIEMode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on the Use audio input feature..
        /// </summary>
        public static string TableCloth_Switch_EnableMicrophone_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableMicrophone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on printer sharing..
        /// </summary>
        public static string TableCloth_Switch_EnablePrinter_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnablePrinter_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this help..
        /// </summary>
        public static string TableCloth_Switch_Help_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Help_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the Adobe Reader installation after starting the sandbox..
        /// </summary>
        public static string TableCloth_Switch_InstallAdobeReader_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallAdobeReader_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the Everyone&apos;s Printer installation after starting the sandbox..
        /// </summary>
        public static string TableCloth_Switch_InstallEveryonesPrinter_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallEveryonesPrinter_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the Hancom Office Viewer installation after starting the sandbox..
        /// </summary>
        public static string TableCloth_Switch_InstallHancomOfficeViewer_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallHancomOfficeViewer_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the RaiDrive installation after starting the sandbox..
        /// </summary>
        public static string TableCloth_Switch_InstallRaiDrive_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallRaiDrive_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Option&gt;.
        /// </summary>
        public static string TableCloth_Switch_Option_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Option_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options: .
        /// </summary>
        public static string TableCloth_Switch_OptionList_Begin {
            get {
                return ResourceManager.GetString("TableCloth_Switch_OptionList_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;File Path&gt;.
        /// </summary>
        public static string TableCloth_Switch_PrivateKeyFilePath_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_PrivateKeyFilePath_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;File Path&gt;.
        /// </summary>
        public static string TableCloth_Switch_PublicKeyFilePath_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_PublicKeyFilePath_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check {0} for the ServiceID..
        /// </summary>
        public static string TableCloth_Switch_ServiceID_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_ServiceID_Help", resourceCulture);
            }
        }
    }
}
