//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SwitchStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SwitchStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.SwitchStrings", typeof(SwitchStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증서 비밀 키 파일 경로를 지정합니다..
        /// </summary>
        public static string TableCloth_Switch_CertPrivateKey_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPrivateKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증서 공개 키 파일 경로를 지정합니다..
        /// </summary>
        public static string TableCloth_Switch_CertPublicKey_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPublicKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (개발자용 기능) 애플리케이션 패키지 설치, 시스템 설정 변경을 건너뛰고 프로그램의 실행 과정만 살펴봅니다..
        /// </summary>
        public static string TableCloth_Switch_DryRun_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_DryRun_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비디오 입력 사용하기 기능을 켭니다..
        /// </summary>
        public static string TableCloth_Switch_EnableCamera_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCamera_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증서를 기능을 켭니다..
        /// </summary>
        public static string TableCloth_Switch_EnableCert_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCert_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer 모드를 활성화합니다..
        /// </summary>
        public static string TableCloth_Switch_EnableIEMode_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableIEMode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오디오 입력 사용하기 기능을 켭니다..
        /// </summary>
        public static string TableCloth_Switch_EnableMicrophone_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableMicrophone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프린터 공유하기 기능을 켭니다..
        /// </summary>
        public static string TableCloth_Switch_EnablePrinter_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnablePrinter_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이 도움말을 표시합니다..
        /// </summary>
        public static string TableCloth_Switch_Help_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Help_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Reader 설치를 샌드박스 시작 후 실행합니다..
        /// </summary>
        public static string TableCloth_Switch_InstallAdobeReader_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallAdobeReader_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모두의 프린터 설치를 샌드박스 시작 후 실행합니다..
        /// </summary>
        public static string TableCloth_Switch_InstallEveryonesPrinter_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallEveryonesPrinter_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한컴오피스 뷰어 설치를 샌드박스 시작 후 실행합니다..
        /// </summary>
        public static string TableCloth_Switch_InstallHancomOfficeViewer_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallHancomOfficeViewer_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaiDrive 설치를 샌드박스 시작 후 실행합니다..
        /// </summary>
        public static string TableCloth_Switch_InstallRaiDrive_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallRaiDrive_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;옵션&gt;.
        /// </summary>
        public static string TableCloth_Switch_Option_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Option_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 옵션: .
        /// </summary>
        public static string TableCloth_Switch_OptionList_Begin {
            get {
                return ResourceManager.GetString("TableCloth_Switch_OptionList_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;파일 경로&gt;.
        /// </summary>
        public static string TableCloth_Switch_PrivateKeyFilePath_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_PrivateKeyFilePath_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;파일 경로&gt;.
        /// </summary>
        public static string TableCloth_Switch_PublicKeyFilePath_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_PublicKeyFilePath_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceID는 {0}을 확인해주세요..
        /// </summary>
        public static string TableCloth_Switch_ServiceID_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_ServiceID_Help", resourceCulture);
            }
        }
    }
}
