//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.UIStringResources", typeof(UIStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Version.
        /// </summary>
        public static string AboutWindow_AppVersionText {
            get {
                return ResourceManager.GetString("AboutWindow_AppVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Version.
        /// </summary>
        public static string AboutWindow_CatalogDateText {
            get {
                return ResourceManager.GetString("AboutWindow_CatalogDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving license information..
        /// </summary>
        public static string AboutWindow_LoadingLicensesMessage {
            get {
                return ResourceManager.GetString("AboutWindow_LoadingLicensesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About This Program.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This build is for development purposes only..
        /// </summary>
        public static string Build_Debug {
            get {
                return ResourceManager.GetString("Build_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Button_AboutButton {
            get {
                return ResourceManager.GetString("Button_AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Button_AppRestartButton {
            get {
                return ResourceManager.GetString("Button_AppRestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Button_BrowseButton {
            get {
                return ResourceManager.GetString("Button_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_CancelButton {
            get {
                return ResourceManager.GetString("Button_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        public static string Button_CheckUpdateButton {
            get {
                return ResourceManager.GetString("Button_CheckUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_CloseButton {
            get {
                return ResourceManager.GetString("Button_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to PFX.
        /// </summary>
        public static string Button_ConvertToPfxButton {
            get {
                return ResourceManager.GetString("Button_ConvertToPfxButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Commandline.
        /// </summary>
        public static string Button_CopyCommandLineButton {
            get {
                return ResourceManager.GetString("Button_CopyCommandLineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Shortcut.
        /// </summary>
        public static string Button_CreateShortcutButton {
            get {
                return ResourceManager.GetString("Button_CreateShortcutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Button_DebugButton {
            get {
                return ResourceManager.GetString("Button_DebugButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Button_InstallButton {
            get {
                return ResourceManager.GetString("Button_InstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Button_LaunchButton {
            get {
                return ResourceManager.GetString("Button_LaunchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Certificates.
        /// </summary>
        public static string Button_MapNpkiCertButton {
            get {
                return ResourceManager.GetString("Button_MapNpkiCertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OkayButton {
            get {
                return ResourceManager.GetString("Button_OkayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Button_OpenHomepageButton {
            get {
                return ResourceManager.GetString("Button_OpenHomepageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Button_PrivacyLink {
            get {
                return ResourceManager.GetString("Button_PrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_RefreshButton {
            get {
                return ResourceManager.GetString("Button_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string Button_ShowSysInfoButton {
            get {
                return ResourceManager.GetString("Button_ShowSysInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the website you want to access, or enter a search term in the search bar in the upper-right corner..
        /// </summary>
        public static string CatalogPage_Instruction {
            get {
                return ResourceManager.GetString("CatalogPage_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string CatalogPage_ItemCountLabel {
            get {
                return ResourceManager.GetString("CatalogPage_ItemCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a service.
        /// </summary>
        public static string CatalogPage_Title {
            get {
                return ResourceManager.GetString("CatalogPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Cert_Availability_Available {
            get {
                return ResourceManager.GetString("Cert_Availability_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Cert_Availability_Expired {
            get {
                return ResourceManager.GetString("Cert_Availability_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in {0} days.
        /// </summary>
        public static string Cert_Availability_ExpireSoon {
            get {
                return ResourceManager.GetString("Cert_Availability_ExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available in {0} days.
        /// </summary>
        public static string Cert_Availability_MayTooEarly {
            get {
                return ResourceManager.GetString("Cert_Availability_MayTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string CertSelectWindow_CertList_Available {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string CertSelectWindow_CertList_CommonName {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CertSelectWindow_CertList_CountryName {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string CertSelectWindow_CertList_Organization {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Unit.
        /// </summary>
        public static string CertSelectWindow_CertList_OrganizationalUnits {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_OrganizationalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Certificate File (signCert.der;signPri.key)|signCert.der;signPri.key|Public Certificate File (*.pfx;*.p12)|*.pfx;*.p12.
        /// </summary>
        public static string CertSelectWindow_FileOpenDialog_FilterText {
            get {
                return ResourceManager.GetString("CertSelectWindow_FileOpenDialog_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the certificate files (signCert.der, signPri.key, *.pfx, *.p12).
        /// </summary>
        public static string CertSelectWindow_FileOpenDialog_Text {
            get {
                return ResourceManager.GetString("CertSelectWindow_FileOpenDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following certificates were found, please select one of them..
        /// </summary>
        public static string CertSelectWindow_InstructionLabel {
            get {
                return ResourceManager.GetString("CertSelectWindow_InstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t see the certificate you&apos;re looking for, click the Find Joint Certificate button to manually find the DER file and KEY file pair, or PFX file..
        /// </summary>
        public static string CertSelectWindow_ManualInstructionLabelText {
            get {
                return ResourceManager.GetString("CertSelectWindow_ManualInstructionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a certificate....
        /// </summary>
        public static string CertSelectWindow_OpenNpkiCertButton {
            get {
                return ResourceManager.GetString("CertSelectWindow_OpenNpkiCertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the certificate.
        /// </summary>
        public static string CertSelectWindow_Title {
            get {
                return ResourceManager.GetString("CertSelectWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Test.
        /// </summary>
        public static string Debug_SimulateFailure {
            get {
                return ResourceManager.GetString("Debug_SimulateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Test.
        /// </summary>
        public static string Debug_SimulateFailurePackageName {
            get {
                return ResourceManager.GetString("Debug_SimulateFailurePackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of software to be installed after sandbox run: {0}.
        /// </summary>
        public static string DetailPage_PackageCountDisplayLabel {
            get {
                return ResourceManager.GetString("DetailPage_PackageCountDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage address: {0}.
        /// </summary>
        public static string DetailPage_UrlLabel {
            get {
                return ResourceManager.GetString("DetailPage_UrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree. I won&apos;t look at this screen for a week..
        /// </summary>
        public static string DisclaimerWindow_AgreeButtonText {
            get {
                return ResourceManager.GetString("DisclaimerWindow_AgreeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are responsible for any failure or damage to any person, business, or organization that occurs while using Tableau, including loss of money, missed tax returns, etc.
        ///
        ///We recommend that you do not use TableCloth for tasks that cannot be performed in a virtual environment and should be performed in a physical PC environment to prevent damage or harm..
        /// </summary>
        public static string DisclaimerWindow_Content {
            get {
                return ResourceManager.GetString("DisclaimerWindow_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be sure to read it..
        /// </summary>
        public static string DisclaimerWindow_Readme {
            get {
                return ResourceManager.GetString("DisclaimerWindow_Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precautions for using TableCloth.
        /// </summary>
        public static string DisclaimerWindow_Title {
            get {
                return ResourceManager.GetString("DisclaimerWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is a tool that installs the requested installers into the sandbox at once. Press the Install button to start the installation..
        /// </summary>
        public static string Hostess_AppInstructionMessage {
            get {
                return ResourceManager.GetString("Hostess_AppInstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth Auto-Installer.
        /// </summary>
        public static string Hostess_AppTitle {
            get {
                return ResourceManager.GetString("Hostess_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate installation script.
        /// </summary>
        public static string Hostess_CustomScript_Title {
            get {
                return ResourceManager.GetString("Hostess_CustomScript_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Hostess_Download_InProgress {
            get {
                return ResourceManager.GetString("Hostess_Download_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TableCloth auto-installer is running in dry run mode..
        /// </summary>
        public static string Hostess_DryRunInstructionMessage {
            get {
                return ResourceManager.GetString("Hostess_DryRunInstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Hostess_Install_Failed {
            get {
                return ResourceManager.GetString("Hostess_Install_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Hostess_Install_InProgress {
            get {
                return ResourceManager.GetString("Hostess_Install_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Hostess_Install_Succeed {
            get {
                return ResourceManager.GetString("Hostess_Install_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website ID you want to use is not specified. The sandbox is now available for use..
        /// </summary>
        public static string Hostess_No_Targets {
            get {
                return ResourceManager.GetString("Hostess_No_Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caveats.
        /// </summary>
        public static string Hostess_PrecautionWindowText {
            get {
                return ResourceManager.GetString("Hostess_PrecautionWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string Hostess_ShowDetailError {
            get {
                return ResourceManager.GetString("Hostess_ShowDetailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precautions for using the site.
        /// </summary>
        public static string Hostess_Warning_Title {
            get {
                return ResourceManager.GetString("Hostess_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you enter is only used inside the program and is discarded..
        /// </summary>
        public static string InputPasswordWindow_Disclaimer {
            get {
                return ResourceManager.GetString("InputPasswordWindow_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A passphrase is required to convert the PFX certificate to a DER and KEY for delivery..
        /// </summary>
        public static string InputPasswordWindow_Instruction {
            get {
                return ResourceManager.GetString("InputPasswordWindow_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX Certificate File Path: {0}.
        /// </summary>
        public static string InputPasswordWindow_PfxPathPrefix {
            get {
                return ResourceManager.GetString("InputPasswordWindow_PfxPathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password to convert the PFX certificate.
        /// </summary>
        public static string InputPasswordWindow_Title {
            get {
                return ResourceManager.GetString("InputPasswordWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Internet Explorer Mode.
        /// </summary>
        public static string Install_EnableIEMode {
            get {
                return ResourceManager.GetString("Install_EnableIEMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Environment.
        /// </summary>
        public static string Install_PrepareEnvironment {
            get {
                return ResourceManager.GetString("Install_PrepareEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Desktop Wallpaper.
        /// </summary>
        public static string Install_SetDesktopWallpaper {
            get {
                return ResourceManager.GetString("Install_SetDesktopWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Protecting Critical Services.
        /// </summary>
        public static string Install_TryProtectCriticalServices {
            get {
                return ResourceManager.GetString("Install_TryProtectCriticalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Environment.
        /// </summary>
        public static string Install_VerifyEnvironment {
            get {
                return ResourceManager.GetString("Install_VerifyEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string MainWindow_Column_Category {
            get {
                return ResourceManager.GetString("MainWindow_Column_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of software required.
        /// </summary>
        public static string MainWindow_Column_PackageCount {
            get {
                return ResourceManager.GetString("MainWindow_Column_PackageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Name.
        /// </summary>
        public static string MainWindow_Column_SiteName {
            get {
                return ResourceManager.GetString("MainWindow_Column_SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Address.
        /// </summary>
        public static string MainWindow_Column_SiteUrl {
            get {
                return ResourceManager.GetString("MainWindow_Column_SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just run it..
        /// </summary>
        public static string MainWindow_JustRunItemText {
            get {
                return ResourceManager.GetString("MainWindow_JustRunItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your preferred option..
        /// </summary>
        public static string MainWindow_SelectOptionsLabelText {
            get {
                return ResourceManager.GetString("MainWindow_SelectOptionsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the sites you want to access on the tablecloth. The site will automatically install the necessary programs for you..
        /// </summary>
        public static string MainWindow_SelectSiteLabelText {
            get {
                return ResourceManager.GetString("MainWindow_SelectSiteLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program didn&apos;t get the catalog file! But we&apos;ll run the sandbox for you..
        /// </summary>
        public static string MainWindow_SelectSiteLabelText_Alt {
            get {
                return ResourceManager.GetString("MainWindow_SelectSiteLabelText_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the catalog file!.
        /// </summary>
        public static string MainWindow_SelectSiteLabelText_Alt2 {
            get {
                return ResourceManager.GetString("MainWindow_SelectSiteLabelText_Alt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth - Keep your computer clean!.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in.
        /// </summary>
        public static string Option_Addin {
            get {
                return ResourceManager.GetString("Option_Addin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-ons.
        /// </summary>
        public static string Option_Addons {
            get {
                return ResourceManager.GetString("Option_Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Preferences.
        /// </summary>
        public static string Option_BasicPreferences {
            get {
                return ResourceManager.GetString("Option_BasicPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Adobe Reader.
        /// </summary>
        public static string Option_InstallAdobeReader {
            get {
                return ResourceManager.GetString("Option_InstallAdobeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Everyones Printer.
        /// </summary>
        public static string Option_InstallEveryonesPrinter {
            get {
                return ResourceManager.GetString("Option_InstallEveryonesPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Hancom Office Viewer.
        /// </summary>
        public static string Option_InstallHancomOfficeViewer {
            get {
                return ResourceManager.GetString("Option_InstallHancomOfficeViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install RaiDrive.
        /// </summary>
        public static string Option_InstallRaiDrive {
            get {
                return ResourceManager.GetString("Option_InstallRaiDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options below allow you to turn on and off features that will be introduced in the new version of the TableCloth program..
        /// </summary>
        public static string Option_LabDescriptionText {
            get {
                return ResourceManager.GetString("Option_LabDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimentals.
        /// </summary>
        public static string Option_LabPreferences {
            get {
                return ResourceManager.GetString("Option_LabPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the new user interface.
        /// </summary>
        public static string Option_NewUIOptIn {
            get {
                return ResourceManager.GetString("Option_NewUIOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites.
        /// </summary>
        public static string Option_Prerequisites {
            get {
                return ResourceManager.GetString("Option_Prerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth uses the Sentry.io service to anonymously collect information about errors that occur during the execution of the Tablecloth program. If you do not want to send data, please uncheck the box below and run Tablecloth again..
        /// </summary>
        public static string Option_TelemetryDescriptionText {
            get {
                return ResourceManager.GetString("Option_TelemetryDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting information to improve features.
        /// </summary>
        public static string Option_TelemetryPreferences {
            get {
                return ResourceManager.GetString("Option_TelemetryPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically collect TableCloth error logs.
        /// </summary>
        public static string Option_UseAutoLogCollecting {
            get {
                return ResourceManager.GetString("Option_UseAutoLogCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Internet Explorer compatibility mode.
        /// </summary>
        public static string Option_UseIEModeCompatList {
            get {
                return ResourceManager.GetString("Option_UseIEModeCompatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using audio input - be careful about revealing personal information!.
        /// </summary>
        public static string Option_UseMicrophoneCheckboxText {
            get {
                return ResourceManager.GetString("Option_UseMicrophoneCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using with printers.
        /// </summary>
        public static string Option_UsePrinterCheckboxText {
            get {
                return ResourceManager.GetString("Option_UsePrinterCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using video input - be careful about exposing personal information!.
        /// </summary>
        public static string Option_UseWebCameraCheckboxText {
            get {
                return ResourceManager.GetString("Option_UseWebCameraCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a search keyword (e.g., Shinhan).
        /// </summary>
        public static string SearchFilter_Watermark {
            get {
                return ResourceManager.GetString("SearchFilter_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking internet connection....
        /// </summary>
        public static string Status_CheckInternetConnection {
            get {
                return ResourceManager.GetString("Status_CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re ready to run..
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking system environment....
        /// </summary>
        public static string Status_EvaluatingRequirementsMet {
            get {
                return ResourceManager.GetString("Status_EvaluatingRequirementsMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the application....
        /// </summary>
        public static string Status_InitializingApplication {
            get {
                return ResourceManager.GetString("Status_InitializingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string Status_InitializingFailed {
            get {
                return ResourceManager.GetString("Status_InitializingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Sentry SDK....
        /// </summary>
        public static string Status_InitSentrySDK {
            get {
                return ResourceManager.GetString("Status_InitSentrySDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading catalog....
        /// </summary>
        public static string Status_LoadingCatalog {
            get {
                return ResourceManager.GetString("Status_LoadingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading images....
        /// </summary>
        public static string Status_LoadingImages {
            get {
                return ResourceManager.GetString("Status_LoadingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading preferences....
        /// </summary>
        public static string Status_LoadingPreferences {
            get {
                return ResourceManager.GetString("Status_LoadingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing the command line....
        /// </summary>
        public static string Status_ParsingCommandLine {
            get {
                return ResourceManager.GetString("Status_ParsingCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a second....
        /// </summary>
        public static string Status_PleaseWait {
            get {
                return ResourceManager.GetString("Status_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth Error.
        /// </summary>
        public static string TitleText_Error {
            get {
                return ResourceManager.GetString("TitleText_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth Info.
        /// </summary>
        public static string TitleText_Info {
            get {
                return ResourceManager.GetString("TitleText_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth Question.
        /// </summary>
        public static string TitleText_Question {
            get {
                return ResourceManager.GetString("TitleText_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth Warning.
        /// </summary>
        public static string TitleText_Warning {
            get {
                return ResourceManager.GetString("TitleText_Warning", resourceCulture);
            }
        }
    }
}
