//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.UIStringResources", typeof(UIStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램 버전.
        /// </summary>
        public static string AboutWindow_AppVersionText {
            get {
                return ResourceManager.GetString("AboutWindow_AppVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카탈로그 버전.
        /// </summary>
        public static string AboutWindow_CatalogDateText {
            get {
                return ResourceManager.GetString("AboutWindow_CatalogDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업데이트 확인.
        /// </summary>
        public static string AboutWindow_CheckUpdateButtonText {
            get {
                return ResourceManager.GetString("AboutWindow_CheckUpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 라이선스 정보를 확인 중입니다..
        /// </summary>
        public static string AboutWindow_LoadingLicensesMessage {
            get {
                return ResourceManager.GetString("AboutWindow_LoadingLicensesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        public static string AboutWindow_OkayButton {
            get {
                return ResourceManager.GetString("AboutWindow_OkayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 홈페이지.
        /// </summary>
        public static string AboutWindow_OpenHomepageButton {
            get {
                return ResourceManager.GetString("AboutWindow_OpenHomepageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개인 정보 처리 방침.
        /// </summary>
        public static string AboutWindow_PrivacyLinkText {
            get {
                return ResourceManager.GetString("AboutWindow_PrivacyLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 정보.
        /// </summary>
        public static string AboutWindow_ShowSysInfoButtonText {
            get {
                return ResourceManager.GetString("AboutWindow_ShowSysInfoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램 정보.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보에 대하여....
        /// </summary>
        public static string CatalogPage_AboutButton {
            get {
                return ResourceManager.GetString("CatalogPage_AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 접속하려는 웹 사이트를 선택하거나, 우측 상단의 검색창에서 검색어를 입력하세요..
        /// </summary>
        public static string CatalogPage_Instruction {
            get {
                return ResourceManager.GetString("CatalogPage_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}개.
        /// </summary>
        public static string CatalogPage_ItemCountLabel {
            get {
                return ResourceManager.GetString("CatalogPage_ItemCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인터넷 뱅킹 서비스 선택.
        /// </summary>
        public static string CatalogPage_Title {
            get {
                return ResourceManager.GetString("CatalogPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용 가능.
        /// </summary>
        public static string Cert_Availability_Available {
            get {
                return ResourceManager.GetString("Cert_Availability_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 만료됨.
        /// </summary>
        public static string Cert_Availability_Expired {
            get {
                return ResourceManager.GetString("Cert_Availability_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}일 후 만료.
        /// </summary>
        public static string Cert_Availability_ExpireSoon {
            get {
                return ResourceManager.GetString("Cert_Availability_ExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}일 후 사용 가능.
        /// </summary>
        public static string Cert_Availability_MayTooEarly {
            get {
                return ResourceManager.GetString("Cert_Availability_MayTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        public static string CertSelectWindow_CancelButtonText {
            get {
                return ResourceManager.GetString("CertSelectWindow_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용 가능 여부.
        /// </summary>
        public static string CertSelectWindow_CertList_Available {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소유자.
        /// </summary>
        public static string CertSelectWindow_CertList_CommonName {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 국가.
        /// </summary>
        public static string CertSelectWindow_CertList_CountryName {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발급기관.
        /// </summary>
        public static string CertSelectWindow_CertList_Organization {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기관.
        /// </summary>
        public static string CertSelectWindow_CertList_OrganizationalUnits {
            get {
                return ResourceManager.GetString("CertSelectWindow_CertList_OrganizationalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX 파일로 변환하기.
        /// </summary>
        public static string CertSelectWindow_ConvertToPfxButtonText {
            get {
                return ResourceManager.GetString("CertSelectWindow_ConvertToPfxButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공동 인증서 파일 (signCert.der;signPri.key)|signCert.der;signPri.key|공동 인증서 파일 (*.pfx;*.p12)|*.pfx;*.p12.
        /// </summary>
        public static string CertSelectWindow_FileOpenDialog_FilterText {
            get {
                return ResourceManager.GetString("CertSelectWindow_FileOpenDialog_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공동 인증서 파일 (signCert.der, signPri.key, *.pfx, *.p12) 열기.
        /// </summary>
        public static string CertSelectWindow_FileOpenDialog_Text {
            get {
                return ResourceManager.GetString("CertSelectWindow_FileOpenDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색된 공동 인증서가 다음과 같습니다. 다음 중 하나를 선택해주세요..
        /// </summary>
        public static string CertSelectWindow_InstructionLabel {
            get {
                return ResourceManager.GetString("CertSelectWindow_InstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 원하는 공동 인증서가 없다면, 직접 공동 인증서 찾기 버튼을 눌러서 직접 DER 파일과 KEY 파일 한 쌍, 혹은 PFX 파일을 찾아주세요..
        /// </summary>
        public static string CertSelectWindow_ManualInstructionLabelText {
            get {
                return ResourceManager.GetString("CertSelectWindow_ManualInstructionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        public static string CertSelectWindow_OkayButtonText {
            get {
                return ResourceManager.GetString("CertSelectWindow_OkayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직접 공동 인증서 찾기....
        /// </summary>
        public static string CertSelectWindow_OpenNpkiCertButton {
            get {
                return ResourceManager.GetString("CertSelectWindow_OpenNpkiCertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로 고침.
        /// </summary>
        public static string CertSelectWindow_RefreshButtonText {
            get {
                return ResourceManager.GetString("CertSelectWindow_RefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색된 공동 인증서 선택.
        /// </summary>
        public static string CertSelectWindow_Title {
            get {
                return ResourceManager.GetString("CertSelectWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 찾아보기....
        /// </summary>
        public static string DetailPage_BrowseButtonText {
            get {
                return ResourceManager.GetString("DetailPage_BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령줄 복사하기.
        /// </summary>
        public static string DetailPage_CopyCommandLineButton {
            get {
                return ResourceManager.GetString("DetailPage_CopyCommandLineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바로 가기 만들기.
        /// </summary>
        public static string DetailPage_CreateShortcutButton {
            get {
                return ResourceManager.GetString("DetailPage_CreateShortcutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Reader 설치하기.
        /// </summary>
        public static string DetailPage_InstallAdobeReader {
            get {
                return ResourceManager.GetString("DetailPage_InstallAdobeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모두의 프린터 설치하기.
        /// </summary>
        public static string DetailPage_InstallEveryonesPrinter {
            get {
                return ResourceManager.GetString("DetailPage_InstallEveryonesPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한컴오피스 뷰어 설치하기.
        /// </summary>
        public static string DetailPage_InstallHancomOfficeViewer {
            get {
                return ResourceManager.GetString("DetailPage_InstallHancomOfficeViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaiDrive 설치하기.
        /// </summary>
        public static string DetailPage_InstallRaiDrive {
            get {
                return ResourceManager.GetString("DetailPage_InstallRaiDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아래 옵션에서 새로운 버전의 식탁보 프로그램에 도입될 예정인 기능을 켜고 끌 수 있습니다..
        /// </summary>
        public static string DetailPage_LabDescriptionText {
            get {
                return ResourceManager.GetString("DetailPage_LabDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 실행하기.
        /// </summary>
        public static string DetailPage_LaunchButton {
            get {
                return ResourceManager.GetString("DetailPage_LaunchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기존 공동 인증서 파일 가져오기.
        /// </summary>
        public static string DetailPage_MapNpkiCertButtonText {
            get {
                return ResourceManager.GetString("DetailPage_MapNpkiCertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 샌드박스 실행 후 설치될 소프트웨어 개수: {0}개.
        /// </summary>
        public static string DetailPage_PackageCountDisplayLabel {
            get {
                return ResourceManager.GetString("DetailPage_PackageCountDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보는 Sentry.io 서비스를 통하여 식탁보 프로그램 실행 도중 발생한 오류 정보를 익명으로 수집합니다. 만약 데이터 보내기를 원하지 않으시면 아래 체크 박스를 선택 해제하신 후 식탁보를 다시 실행해주세요..
        /// </summary>
        public static string DetailPage_TelemetryDescriptionText {
            get {
                return ResourceManager.GetString("DetailPage_TelemetryDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기능 개선을 위한 정보 수집.
        /// </summary>
        public static string DetailPage_TelemetryPreferences {
            get {
                return ResourceManager.GetString("DetailPage_TelemetryPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 홈페이지 주소: {0}.
        /// </summary>
        public static string DetailPage_UrlLabel {
            get {
                return ResourceManager.GetString("DetailPage_UrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 오류 로그 자동 수집.
        /// </summary>
        public static string DetailPage_UseAutoLogCollecting {
            get {
                return ResourceManager.GetString("DetailPage_UseAutoLogCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer 호환성 모드 사용.
        /// </summary>
        public static string DetailPage_UseIEModeCompatList {
            get {
                return ResourceManager.GetString("DetailPage_UseIEModeCompatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오디오 입력 사용하기 - 개인 정보 노출에 주의하세요!.
        /// </summary>
        public static string DetailPage_UseMicrophoneCheckboxText {
            get {
                return ResourceManager.GetString("DetailPage_UseMicrophoneCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프린터 같이 사용하기.
        /// </summary>
        public static string DetailPage_UsePrinterCheckboxText {
            get {
                return ResourceManager.GetString("DetailPage_UsePrinterCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비디오 입력 사용하기 - 개인 정보 노출에 주의하세요!.
        /// </summary>
        public static string DetailPage_UseWebCameraCheckboxText {
            get {
                return ResourceManager.GetString("DetailPage_UseWebCameraCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로운 사용자 인터페이스 사용.
        /// </summary>
        public static string DetailPage_V2UIOptIn {
            get {
                return ResourceManager.GetString("DetailPage_V2UIOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 동의합니다. 일주일 동안 이 화면을 보지 않겠습니다..
        /// </summary>
        public static string DisclaimerWindow_AgreeButtonText {
            get {
                return ResourceManager.GetString("DisclaimerWindow_AgreeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보를 사용 중 발생하는 개인, 기업, 기관의 금전 손실, 세금 신고 누락 등을 비롯한 어떠한 장애나 손해에 대해서는 사용자 본인에게 책임이 있습니다.
        ///
        ///가상 환경이 아닌 실제 컴퓨터 환경에서 실행되어야 손해나 피해가 발생하지 않는 작업은 식탁보를 이용하지 않고 실제 PC 환경에서 사용하는 것을 권장합니다..
        /// </summary>
        public static string DisclaimerWindow_Content {
            get {
                return ResourceManager.GetString("DisclaimerWindow_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 꼭 읽어주세요..
        /// </summary>
        public static string DisclaimerWindow_Readme {
            get {
                return ResourceManager.GetString("DisclaimerWindow_Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 사용 시 주의 사항.
        /// </summary>
        public static string DisclaimerWindow_Title {
            get {
                return ResourceManager.GetString("DisclaimerWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램 정보.
        /// </summary>
        public static string Hostess_AboutButtonText {
            get {
                return ResourceManager.GetString("Hostess_AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이 프로그램은 요청받은 설치 프로그램들을 샌드 박스 안에 한번에 설치해주는 도구입니다. 설치하기 버튼을 누르면 설치가 시작됩니다..
        /// </summary>
        public static string Hostess_AppInstructionMessage {
            get {
                return ResourceManager.GetString("Hostess_AppInstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 자동 설치 프로그램.
        /// </summary>
        public static string Hostess_AppTitle {
            get {
                return ResourceManager.GetString("Hostess_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        public static string Hostess_CloseButtonText {
            get {
                return ResourceManager.GetString("Hostess_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 별도 설치 스크립트.
        /// </summary>
        public static string Hostess_CustomScript_Title {
            get {
                return ResourceManager.GetString("Hostess_CustomScript_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다운로드 중....
        /// </summary>
        public static string Hostess_Download_InProgress {
            get {
                return ResourceManager.GetString("Hostess_Download_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 자동 설치 프로그램이 Dry Run 모드로 실행 중입니다..
        /// </summary>
        public static string Hostess_DryRunInstructionMessage {
            get {
                return ResourceManager.GetString("Hostess_DryRunInstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오류.
        /// </summary>
        public static string Hostess_ErrorDialogTitle {
            get {
                return ResourceManager.GetString("Hostess_ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설치 실패.
        /// </summary>
        public static string Hostess_Install_Failed {
            get {
                return ResourceManager.GetString("Hostess_Install_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설치하는 중....
        /// </summary>
        public static string Hostess_Install_InProgress {
            get {
                return ResourceManager.GetString("Hostess_Install_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설치 완료.
        /// </summary>
        public static string Hostess_Install_Succeed {
            get {
                return ResourceManager.GetString("Hostess_Install_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설치하기.
        /// </summary>
        public static string Hostess_InstallButtonText {
            get {
                return ResourceManager.GetString("Hostess_InstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows PowerShell 실행 파일을 찾을 수 없어 설치 스크립트를 실행할 수 없습니다..
        /// </summary>
        public static string Hostess_No_PowerShell_Error {
            get {
                return ResourceManager.GetString("Hostess_No_PowerShell_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이용하려는 웹 사이트 아이디가 지정되지 않았습니다. 샌드박스는 지금부터 사용하실 수 있어요..
        /// </summary>
        public static string Hostess_No_Targets {
            get {
                return ResourceManager.GetString("Hostess_No_Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주의 사항.
        /// </summary>
        public static string Hostess_PrecautionWindowText {
            get {
                return ResourceManager.GetString("Hostess_PrecautionWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 질문.
        /// </summary>
        public static string Hostess_QuestionDialogTitle {
            get {
                return ResourceManager.GetString("Hostess_QuestionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자세히 보기.
        /// </summary>
        public static string Hostess_ShowDetailError {
            get {
                return ResourceManager.GetString("Hostess_ShowDetailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사이트 이용 시 주의 사항.
        /// </summary>
        public static string Hostess_Warning_Title {
            get {
                return ResourceManager.GetString("Hostess_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지금 이 프로그램이 실행되는 환경은 윈도우 샌드박스 환경이 아닌 것 같습니다. 그래도 계속 실행하시겠습니까?.
        /// </summary>
        public static string Hostess_WarningForNonSandboxEnvironment {
            get {
                return ResourceManager.GetString("Hostess_WarningForNonSandboxEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        public static string InputPasswordWindow_CancelButton {
            get {
                return ResourceManager.GetString("InputPasswordWindow_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 입력하시는 암호는 프로그램 내부에서만 사용되고 폐기됩니다..
        /// </summary>
        public static string InputPasswordWindow_Disclaimer {
            get {
                return ResourceManager.GetString("InputPasswordWindow_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX 인증서를 DER과 KEY로 변환해서 전달하기 위해 비밀 번호 입력이 필요합니다..
        /// </summary>
        public static string InputPasswordWindow_Instruction {
            get {
                return ResourceManager.GetString("InputPasswordWindow_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        public static string InputPasswordWindow_OkayButton {
            get {
                return ResourceManager.GetString("InputPasswordWindow_OkayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX 인증서 파일 경로: {0}.
        /// </summary>
        public static string InputPasswordWindow_PfxPathPrefix {
            get {
                return ResourceManager.GetString("InputPasswordWindow_PfxPathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX 인증서 변환을 위한 비밀 번호 입력.
        /// </summary>
        public static string InputPasswordWindow_Title {
            get {
                return ResourceManager.GetString("InputPasswordWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정보.
        /// </summary>
        public static string MainWindow_AboutButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 부가 기능.
        /// </summary>
        public static string MainWindow_Addons {
            get {
                return ResourceManager.GetString("MainWindow_Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기본 설정.
        /// </summary>
        public static string MainWindow_BasicPreferences {
            get {
                return ResourceManager.GetString("MainWindow_BasicPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 찾아보기....
        /// </summary>
        public static string MainWindow_BrowseButtonText {
            get {
                return ResourceManager.GetString("MainWindow_BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        public static string MainWindow_CloseButtonText {
            get {
                return ResourceManager.GetString("MainWindow_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 분류.
        /// </summary>
        public static string MainWindow_Column_Category {
            get {
                return ResourceManager.GetString("MainWindow_Column_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 필요 소프트웨어 개수.
        /// </summary>
        public static string MainWindow_Column_PackageCount {
            get {
                return ResourceManager.GetString("MainWindow_Column_PackageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 웹 사이트 이름.
        /// </summary>
        public static string MainWindow_Column_SiteName {
            get {
                return ResourceManager.GetString("MainWindow_Column_SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 웹 사이트 주소.
        /// </summary>
        public static string MainWindow_Column_SiteUrl {
            get {
                return ResourceManager.GetString("MainWindow_Column_SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Reader 설치하기.
        /// </summary>
        public static string MainWindow_InstallAdobeReader {
            get {
                return ResourceManager.GetString("MainWindow_InstallAdobeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모두의 프린터 설치하기.
        /// </summary>
        public static string MainWindow_InstallEveryonesPrinter {
            get {
                return ResourceManager.GetString("MainWindow_InstallEveryonesPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한컴오피스 뷰어 설치하기.
        /// </summary>
        public static string MainWindow_InstallHancomOfficeViewer {
            get {
                return ResourceManager.GetString("MainWindow_InstallHancomOfficeViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaiDrive 설치하기.
        /// </summary>
        public static string MainWindow_InstallRaiDrive {
            get {
                return ResourceManager.GetString("MainWindow_InstallRaiDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그냥 실행해주세요..
        /// </summary>
        public static string MainWindow_JustRunItemText {
            get {
                return ResourceManager.GetString("MainWindow_JustRunItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아래 옵션에서 새로운 버전의 식탁보 프로그램에 도입될 예정인 기능을 켜고 끌 수 있습니다..
        /// </summary>
        public static string MainWindow_LabDescriptionText {
            get {
                return ResourceManager.GetString("MainWindow_LabDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 실험실.
        /// </summary>
        public static string MainWindow_LabPreferences {
            get {
                return ResourceManager.GetString("MainWindow_LabPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 샌드박스 실행.
        /// </summary>
        public static string MainWindow_LaunchSandboxButtonText {
            get {
                return ResourceManager.GetString("MainWindow_LaunchSandboxButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기존 공동 인증서 파일 가져오기.
        /// </summary>
        public static string MainWindow_MapNpkiCertButtonText {
            get {
                return ResourceManager.GetString("MainWindow_MapNpkiCertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다시 불러오기 (프로그램 다시 실행).
        /// </summary>
        public static string MainWindow_ReloadCatalog {
            get {
                return ResourceManager.GetString("MainWindow_ReloadCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 찾고 싶은 웹 사이트의 이름, 분류, 도메인 주소를 입력하세요. (예: 신한, 보험, iros).
        /// </summary>
        public static string MainWindow_SearchFilter_Watermark {
            get {
                return ResourceManager.GetString("MainWindow_SearchFilter_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 원하는 옵션을 선택해주세요..
        /// </summary>
        public static string MainWindow_SelectOptionsLabelText {
            get {
                return ResourceManager.GetString("MainWindow_SelectOptionsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 위에서 접속할 사이트들을 선택해주세요. 사이트에서 필요한 프로그램들을 자동으로 설치해드려요..
        /// </summary>
        public static string MainWindow_SelectSiteLabelText {
            get {
                return ResourceManager.GetString("MainWindow_SelectSiteLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카탈로그 파일을 가져오지 못했어요! 그래도 샌드박스는 대신 실행해드려요..
        /// </summary>
        public static string MainWindow_SelectSiteLabelText_Alt {
            get {
                return ResourceManager.GetString("MainWindow_SelectSiteLabelText_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카탈로그 파일을 가져오지 못했어요!.
        /// </summary>
        public static string MainWindow_SelectSiteLabelText_Alt2 {
            get {
                return ResourceManager.GetString("MainWindow_SelectSiteLabelText_Alt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바로 가기 만들기.
        /// </summary>
        public static string MainWindow_ShortcutButtonText {
            get {
                return ResourceManager.GetString("MainWindow_ShortcutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보는 Sentry.io 서비스를 통하여 식탁보 프로그램 실행 도중 발생한 오류 정보를 익명으로 수집합니다. 만약 데이터 보내기를 원하지 않으시면 아래 체크 박스를 선택 해제하신 후 식탁보를 다시 실행해주세요..
        /// </summary>
        public static string MainWindow_TelemetryDescriptionText {
            get {
                return ResourceManager.GetString("MainWindow_TelemetryDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기능 개선을 위한 정보 수집.
        /// </summary>
        public static string MainWindow_TelemetryPreferences {
            get {
                return ResourceManager.GetString("MainWindow_TelemetryPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 - 컴퓨터를 깨끗하게 사용하세요!.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 오류 로그 자동 수집.
        /// </summary>
        public static string MainWindow_UseAutoLogCollecting {
            get {
                return ResourceManager.GetString("MainWindow_UseAutoLogCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer 호환성 모드 사용.
        /// </summary>
        public static string MainWindow_UseIEModeCompatList {
            get {
                return ResourceManager.GetString("MainWindow_UseIEModeCompatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오디오 입력 사용하기 - 개인 정보 노출에 주의하세요!.
        /// </summary>
        public static string MainWindow_UseMicrophoneCheckboxText {
            get {
                return ResourceManager.GetString("MainWindow_UseMicrophoneCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프린터 같이 사용하기.
        /// </summary>
        public static string MainWindow_UsePrinterCheckboxText {
            get {
                return ResourceManager.GetString("MainWindow_UsePrinterCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비디오 입력 사용하기 - 개인 정보 노출에 주의하세요!.
        /// </summary>
        public static string MainWindow_UseWebCameraCheckboxText {
            get {
                return ResourceManager.GetString("MainWindow_UseWebCameraCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로운 사용자 인터페이스 사용.
        /// </summary>
        public static string MainWindow_V2UIOptIn {
            get {
                return ResourceManager.GetString("MainWindow_V2UIOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색 키워드 입력 (예: 신한, 보험).
        /// </summary>
        public static string MainWindowV2_SearchFilter_Watermark {
            get {
                return ResourceManager.GetString("MainWindowV2_SearchFilter_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 식탁보 - 컴퓨터를 깨끗하게 사용하세요!.
        /// </summary>
        public static string MainWindowV2_Title {
            get {
                return ResourceManager.GetString("MainWindowV2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지금부터 {0}개 프로그램의 설치 과정이 시작됩니다. 모든 프로그램의 설치가 끝나면 자동으로 {1} 홈페이지가 열립니다..
        /// </summary>
        public static string Script_InstructionMessage {
            get {
                return ResourceManager.GetString("Script_InstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 안내.
        /// </summary>
        public static string Script_InstructionTitleText {
            get {
                return ResourceManager.GetString("Script_InstructionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인터넷 연결 상태 확인 중....
        /// </summary>
        public static string Status_CheckInternetConnection {
            get {
                return ResourceManager.GetString("Status_CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 실행 준비가 완료되었습니다..
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 환경 확인 중....
        /// </summary>
        public static string Status_EvaluatingRequirementsMet {
            get {
                return ResourceManager.GetString("Status_EvaluatingRequirementsMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 애플리케이션 초기화 중....
        /// </summary>
        public static string Status_InitializingApplication {
            get {
                return ResourceManager.GetString("Status_InitializingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오류가 발생했습니다..
        /// </summary>
        public static string Status_InitializingFailed {
            get {
                return ResourceManager.GetString("Status_InitializingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentry SDK 초기화 중....
        /// </summary>
        public static string Status_InitSentrySDK {
            get {
                return ResourceManager.GetString("Status_InitSentrySDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카탈로그 불러오는 중....
        /// </summary>
        public static string Status_LoadingCatalog {
            get {
                return ResourceManager.GetString("Status_LoadingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미지 불러오는 중....
        /// </summary>
        public static string Status_LoadingImages {
            get {
                return ResourceManager.GetString("Status_LoadingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 환경 설정 불러오는 중....
        /// </summary>
        public static string Status_LoadingPreferences {
            get {
                return ResourceManager.GetString("Status_LoadingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령줄 분석 중....
        /// </summary>
        public static string Status_ParsingCommandLine {
            get {
                return ResourceManager.GetString("Status_ParsingCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잠시만 기다려 주세요..
        /// </summary>
        public static string Status_PleaseWait {
            get {
                return ResourceManager.GetString("Status_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 오류.
        /// </summary>
        public static string TitleText_Error {
            get {
                return ResourceManager.GetString("TitleText_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 정보.
        /// </summary>
        public static string TitleText_Info {
            get {
                return ResourceManager.GetString("TitleText_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 확인.
        /// </summary>
        public static string TitleText_Question {
            get {
                return ResourceManager.GetString("TitleText_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 경고.
        /// </summary>
        public static string TitleText_Warning {
            get {
                return ResourceManager.GetString("TitleText_Warning", resourceCulture);
            }
        }
    }
}
