//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SwitchStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SwitchStrings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth.Resources.Resources.SwitchStrings", typeof(SwitchStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Specifies the path to the certificate secret key file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_CertPrivateKey_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPrivateKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the path to the certificate public key file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_CertPublicKey_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPublicKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Features for developers) Skip installing application packages, changing system settings, and just watch the program run.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_DryRun_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_DryRun_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn on the Use video input feature.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnableCamera_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCamera_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn on certificates as a feature.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnableCert_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCert_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Internet Explorer mode.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnableIEMode_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableIEMode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn on the Use audio input feature.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnableMicrophone_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableMicrophone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn on printer sharing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnablePrinter_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnablePrinter_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show this help.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_Help_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Help_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run the Adobe Reader installation after starting the sandbox.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_InstallAdobeReader_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallAdobeReader_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run the Everyone&apos;s Printer installation after starting the sandbox.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_InstallEveryonesPrinter_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallEveryonesPrinter_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run the Hancom Office Viewer installation after starting the sandbox.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_InstallHancomOfficeViewer_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallHancomOfficeViewer_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run the RaiDrive installation after starting the sandbox.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_InstallRaiDrive_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallRaiDrive_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Option&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_Option_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Option_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_OptionList_Begin {
            get {
                return ResourceManager.GetString("TableCloth_Switch_OptionList_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;File Path&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_PrivateKeyFilePath_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_PrivateKeyFilePath_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;File Path&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_PublicKeyFilePath_Arg {
            get {
                return ResourceManager.GetString("TableCloth_Switch_PublicKeyFilePath_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check {0} for the ServiceID.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_ServiceID_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_ServiceID_Help", resourceCulture);
            }
        }
    }
}
