<Project Sdk="MSTest.Sdk/4.0.1">
  <PropertyGroup>
    <TargetFramework>net11.0-windows10.0.18362.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TableCloth.ManagedAi.OpenAi/TableCloth.ManagedAi.OpenAi.csproj" />
    <ProjectReference Include="../TableCloth.ManagedAi.Windows/TableCloth.ManagedAi.Windows.csproj" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Update="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Update="MSTest.TestFramework" Version="4.0.2" />
  </ItemGroup>
</Project>
