//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstantStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantStrings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spork.Resources.ConstantStrings", typeof(ConstantStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   https://yourtablecloth.app/TableClothCatalog/Catalog.xml과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CatalogUrl {
            get {
                return ResourceManager.GetString("CatalogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FamiliarUserAgentText {
            get {
                return ResourceManager.GetString("FamiliarUserAgentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   github.com과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GitHub_Domain {
            get {
                return ResourceManager.GetString("GitHub_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://yourtablecloth.app/TableClothCatalog/sites.xml과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IEModePolicyXmlUrl {
            get {
                return ResourceManager.GetString("IEModePolicyXmlUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://yourtablecloth.app/TableClothCatalog/images과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageUrlPrefix {
            get {
                return ResourceManager.GetString("ImageUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueryString_Timestamp_Key {
            get {
                return ResourceManager.GetString("QueryString_Timestamp_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://785e3f46849c403bb6c323d7a9eaad91@o77541.ingest.sentry.io/5915832과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SentryDsn {
            get {
                return ResourceManager.GetString("SentryDsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --cert-private-key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_CertPrivateKey {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --cert-public-key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_CertPublicKey {
            get {
                return ResourceManager.GetString("TableCloth_Switch_CertPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --dry-run과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_DryRun {
            get {
                return ResourceManager.GetString("TableCloth_Switch_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --enable-camera과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnableCamera {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --enable-cert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnableCert {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --enable-ie-mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnableIEMode {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableIEMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --enable-microphone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnableMicrophone {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnableMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --enable-printer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_EnablePrinter {
            get {
                return ResourceManager.GetString("TableCloth_Switch_EnablePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_Help {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --ignore--과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_IgnoreSwitch {
            get {
                return ResourceManager.GetString("TableCloth_Switch_IgnoreSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --install-adobe-reader과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_InstallAdobeReader {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallAdobeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --install-everyones-printer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_InstallEveryonesPrinter {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallEveryonesPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --install-hancom-office-viewer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_InstallHancomOfficeViewer {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallHancomOfficeViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --install-rai-drive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_InstallRaiDrive {
            get {
                return ResourceManager.GetString("TableCloth_Switch_InstallRaiDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_Prefix {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --simulate-failure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_SimulateFailure {
            get {
                return ResourceManager.GetString("TableCloth_Switch_SimulateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TableCloth_Switch_Version {
            get {
                return ResourceManager.GetString("TableCloth_Switch_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserAgentText {
            get {
                return ResourceManager.GetString("UserAgentText", resourceCulture);
            }
        }
    }
}
